using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;

public class DataTransmissionScript : MonoBehaviour
{
    public static string gate;
    public static string homeTeam;
    public static string awayTeam;
    public static string playerTeam;
    public static string playerRider;
    public static string playerLeagueTeam;
    public static string playerGPRider;
    public static string tournamentTrack;
    public static int leagueActive;
    public static int GPActive;
    public static int GoatsPoints;
    public static int HammersPoints;
    public static int LionsPoints;
    public static int AngelsPoints;
    public static int WarriorsPoints;
    public static int BullsPoints;
    public static int GullsPoints;
    public static int WolvesPoints;
    public static int BartZmiaczekPoints;
    public static int LoenMaesenPoints;
    public static int MakijJanikPoints;
    public static int FriedMiedgrenPoints;
    public static int RobBlamPoints;
    public static int DavidBanglyPoints;
    public static int PratKudkaPoints;
    public static int TeuWuffPoints;
    public static int MiartenVakliPoints;
    public static int JimiDyolaPoints;
    public static int MikkiMikkelPoints;
    public static int JacksonHolesonPoints;
    public static int MaxiFirkePoints;
    public static int AndronThomPoints;
    public static int KjalNiassonPoints;
    public static int AndijLiewedPoints;
    public static int BartZmiaczekPointsTournament;
    public static int LoenMaesenPointsTournament;
    public static int MakijJanikPointsTournament;
    public static int FriedMiedgrenPointsTournament;
    public static int RobBlamPointsTournament;
    public static int DavidBanglyPointsTournament;
    public static int PratKudkaPointsTournament;
    public static int TeuWuffPointsTournament;
    public static int MiartenVakliPointsTournament;
    public static int JimiDyolaPointsTournament;
    public static int MikkiMikkelPointsTournament;
    public static int JacksonHolesonPointsTournament;
    public static int MaxiFirkePointsTournament;
    public static int AndronThomPointsTournament;
    public static int KjalNiassonPointsTournament;
    public static int AndijLiewedPointsTournament;
    public static int lastTraining;
    public static int lastLeagueMatch;
    public static int lastTournament;
    public static int heatCounter;
    public static int homeTeamScore;
    public static int awayTeamScore;
    public static int lineCounter;
    public static int pointsGateOne;
    public static int pointsGateTwo;
    public static int pointsGateThree;
    public static int pointsGateFour;
    public static int sentFromLeague;
    public static int sentFromGP;
    public static int currentRound;
    public static int leagueLineCounter;
    public static TextAsset programme;
}
